### ISSUE TITLE
StyleGANに必要なmoduleを教えて下さい

### ISSUE THREAD

**Issue by wan2355** [ayukat1016/gan_sample#13]
帰宅前に手元のPC-Linux（manjaro-Linux, 仮想環境のpythonは3.7.7）で試しに動作させたところ容易に動作しました。
（GPUが８GBしかないため、画像は128とし、保存する間隔もdefaultの4倍以上に設定しました。）

最後にscript全体を引数で走らせる記載は私も大好きです。
（他の人も真似してくれないかしら。）

1.
同僚がこれを見て、大容量のGPUをつんだwndows10で試したいとせがまれました。
すでにanacondaはinstallされていますが、今回のStyleGANを動させるのに不足なmoduleを特定できませんでした。
可能であれば、何が必要なのか教えていただけませんか。

2.
保存されるmodelですが、学習が完了するまですべてを保存する必要はないと考えてますが、正しいでしょうか。
fileサイズがかなり大きいので、defaultの４倍の間隔でも大変です。
今の所、学習を途中でとめる時点でのmodelのみを保存し、それ以前は消去します。
ただし学習が最終段階に近づいた時点で、保存間隔を狭め、modelも残していく予定です。
このやり方で大丈夫でしょうか。

3.
今回のcodeを用いて、他のdata-setを試す事は可能でしょうか。
我々は工業材料の電子顕微鏡の画像を扱っており、対象は人ではなく、画像もgray-scaleです。
もし修正したほうが良い所があればご指摘くださると助かります。

以上よろしくお願いします。

PS:今回のdemo画像は個人的には楽しみですが、会社で結果みるには誤解を招きそうで少しハラハラしてます（笑）。

**Comment by h-s-dev** [comment]
>同僚がこれを見て、大容量のGPUをつんだwndows10で試したいとせがまれました。
>すでにanacondaはinstallされていますが、今回のStyleGANを動させるのに不足なmoduleを特定できませんでした。
>可能であれば、何が必要なのか教えていただけませんか。

google colaboratory上で作成したrequirement.txtを添付しますので、そちらをご確認ください。
[requirement.txt](https://github.com/ayukat1016/gan_sample/files/6272777/requirement.txt)

> 保存されるmodelですが、学習が完了するまですべてを保存する必要はないと考えてますが、正しいでしょうか。
> fileサイズがかなり大きいので、defaultの４倍の間隔でも大変です。
> 今の所、学習を途中でとめる時点でのmodelのみを保存し、それ以前は消去します。
> ただし学習が最終段階に近づいた時点で、保存間隔を狭め、modelも残していく予定です。
> このやり方で大丈夫でしょうか。

良いと思います
私はFIDが良い値になった場合のモデルファイルだけを残していました。

> 今回のcodeを用いて、他のdata-setを試す事は可能でしょうか。
> 我々は工業材料の電子顕微鏡の画像を扱っており、対象は人ではなく、画像もgray-scaleです。
> もし修正したほうが良い所があればご指摘くださると助かります。

gray scaleではない画像は試された方がいるようで、それについては動作したようです。
確かCelebAというdatasetだったかと思います。
gray scaleは想定していないので、改修は非常に難しくなると思います。
group convやupsampling時にbilinearを独自実装(NVIDIAが)したりしているので、それらに対して辻褄を合わせるのは至難の技だと思います。

**Comment by wan2355** [comment]
h-s-dev 様

回答ありがとうございます。
最後の回答について質問させてください。

今回のモデルはRBGの人の画像を対象にしておりますが、人以外のRGB画像は難しいということでしょうか。

**Comment by h-s-dev** [comment]
> 今回のモデルはRBGの人の画像を対象にしておりますが、人以外のRGB画像は難しいということでしょうか。

論文では人以外にも部屋の写真、車の写真などを生成しているようなので、人だけではないかと思います。
実際のところ、試してみないと分からないとは思いますが。
私は業務で人以外の物体についてStyleGAN2で生成を行いました。
生成画像はわりと良い感じになったと思います。
StyleGAN2で生成した画像を組み込み、semantic segmentationの学習を行ったところ多少精度が上がりました。

下記がStyleGAN2の論文になります。
こちらもご参考にされると良いかと思います。
https://arxiv.org/pdf/1912.04958.pdf

**Comment by wan2355** [comment]
h-s-dev 様

ありがとうございます。
こちらでも試してみます。

**Comment by wan2355** [comment]
半日ほどfidが表示さず、質問を書いていましたところ、つい先程回復しました。
なぜでしょう？
logが大きいと読み込みに時間がかかるのでしょうか。
ですので、以下途中経過になります。

手元のPCで動作させて６日ほど立ちました（4/7 夜開始）。
昨晩、原因不明でprogramがfreezeしてしまいました。
キーボードも受け付けてくれませんでした　(tmuxを使ってますが、まさかそれが原因？)。
やむえずPCを再起動して、再度programを動作させました。

4日ほど立った時点でfidが最小になって、再び上昇しました。
fidが悪くなったにもかかわらず、画像の質は向上しているようでした。
現在も画質は向上してますが、悪くなるときもあるようです。
画像サイズが128x128pxですので、ぼちぼち限界でしょうか。

以下にtensorboardの一部を添付しました。
![2021-04-13_16 36 24](https://user-images.githubusercontent.com/60186162/114515017-de9f7c00-9c76-11eb-8db7-17c750518a7a.jpg)


生成される画像の質が良くなってきていますが、顔や体がやや歪です。
水着の色や形はリアリティが高く、感心しています。
このような画像が手元のPCでも容易に生成できるように、programを作成されましたh-s-dev 様に感謝します。

現状の画像を付けておきます。
![2021-04-13_16 24 36](https://user-images.githubusercontent.com/60186162/114513155-d9413200-9c74-11eb-9703-d515c3390ce7.jpg)

**Comment by h-s-dev** [comment]
> 半日ほどfidが表示さず、質問を書いていましたところ、つい先程回復しました。
なぜでしょう？
logが大きいと読み込みに時間がかかるのでしょうか。

fidの計算はofficialの実装でV100を使用してもかなり時間がかかります。
あとは私の移植が最適化されていないために遅い可能性があります。
こう直したほうが良いなどの改善点がありましたら、コードを修正しpull requestを上げてください。

> 画像サイズが128x128pxですので、ぼちぼち限界でしょうか。

128 × 128の場合は情報量が少ないので、私が試した時も良い精度の画像を生成することは難しかったです。
256 × 256でも今ひとつの精度だったので、最終的には512 × 512の画像を使用しました。
Google Colabo proを5回線ほど契約し、V100が出るまでGPUガちゃを毎日行い、3ヶ月ほど色々試してようやく生成したのが、サンプルコードのトップに掲載している画像になります。

**Comment by wan2355** [comment]
h-s-dev様
回答ありがとうございます。
あの結果を出すのは大変な仕事量ですね。
こちらも先程まで動かしていましたが、128px では限界のようですので、やめることにしました。
programについては読み切れていませんが、参考になることがあればご連絡します。

他の人の参考までにtensorboardと画像を貼り付けておきます。
128x128で約9日稼働後の結果です。
3回に分けたので、同じグラフが3つあります。
各グラフの最後がfidです。

ここまでの画像を見ていると、顔や腕の表現が難しいようです。
胸や体幹、水着（模様は微妙）、背景は自然な感じがします。
波長が長い構造は容易だが、短いものは難しい？
当然か。。。

![2021-04-16_9 37 43](https://user-images.githubusercontent.com/60186162/114955840-847e0100-9e98-11eb-87b6-ebb516589637.jpg)
![2021-04-16_9 38 02](https://user-images.githubusercontent.com/60186162/114955847-88118800-9e98-11eb-86e4-3fbeb103a61b.jpg)
![38400_fake_predict](https://user-images.githubusercontent.com/60186162/114955858-8c3da580-9e98-11eb-8057-90288e56c5da.png)

**Comment by h-s-dev** [comment]
> ここまでの画像を見ていると、顔や腕の表現が難しいようです。
胸や体幹、水着（模様は微妙）、背景は自然な感じがします。
波長が長い構造は容易だが、短いものは難しい？
当然か。。。

顔は細かいので難易度は高いですが、512で学習を頑張るとある程度は見れる感じになると思います。
顔と体がそれなりに見れるようになっても最後は手や指が綺麗に生成されないことが多いです。

データ数は2万件ぐらいですが、augmentationを行っているので元のデータ数は2000件ほどです。
もしかしたら元のバリエーションが足りないのかもしれません。
サイズ512をGoogle colaboで学習するとバッチ数が4と少なくなってしまうので、もしかしたらそれが原因かもしれません。

良い画像が生成できたら、またご連絡ください。
