### ISSUE TITLE
コード内のVariable()について

### ISSUE THREAD

**Issue by kuri54** [ayukat1016/gan_sample#16]
とても素晴らしい内容の書籍で、参考になる内容ばかりです！
さて、書籍内のコードでお伺いしたいことがあってIssueにあげさせていただきます。

コード内にVariable関数が頻出しています。
Variable関数はPyTorch 0.4でTensorに統合され、それからは非推奨の書き方とされています。
手元でVariable関数なしのコードを試してみましたが、結果に大きな違いはないようです。

何か意図があってのことなのでしょうか？
ご教示頂ければ嬉しいです。

**Comment by h-s-dev** [comment]
> コード内にVariable関数が頻出しています。

こちらはどの章になりますでしょうか？

**Comment by kuri54** [comment]
お返事いただき、ありがとうございます。

どこの部分かを明示するのを失念していました。
わかりにくい書き方をしてしまって申し訳ありませんでした。

読ませていただいた限りなのですが、Variable関数は4章、5章（CycleGAN）、6章、7章、8章内のコード（主に学習ループあたり）にみられます。  

ex. section8_1-AnoGAN.ipynbの231-245（書籍 p.348）

```
for epoch in range(EPOCHS):
    loss_d_sum = 0
    loss_g_sum = 0
    
    for i,(x, x_val) in enumerate(zip(train_loader, val_loader)):
        
        model_G.train()
        model_D.train()
        
        # set values
        y_true = Variable(torch.ones(x.size()[0])).to(device)
        y_fake = Variable(torch.zeros(x.size()[0])).to(device)
        
        x = Variable(x).to(device)
        z = Variable(init.normal(torch.Tensor(x.size()[0],EMBED_SIZE, 1, 1),mean=0,std=0.1)).to(device)
```

> 手元でVariable関数なしのコードを試してみましたが、結果に大きな違いはないようです。

試したのは8章のコードです。

**Comment by h-s-dev** [comment]
７章に関に関しては下記の１箇所のみとなります。
```
real_imgs = Variable(imgs.type(self.Tensor), requires_grad=False)
```
これは
```
real_imgs = imgs.type(self.Tensor)
real_imgs.requires_grad = False
```
を１行で書けるため、そのように記載しています。
ただ、このケースではrequires_gradの初期値はFalseなので、わざわざ設定しなくも良かったかもしれません。

**Comment by kuri54** [comment]
お返事いただき、ありがとうございます。

> ```
> real_imgs = imgs.type(self.Tensor)
> real_imgs.requires_grad = False
> ```
> を１行で書けるため、そのように記載しています。
> ただ、このケースではrequires_gradの初期値はFalseなので、わざわざ設定しなくも良かったかもしれません。

なるほど。そういう意図があったんですね。
他の箇所もそうなんだと理解します。

ありがとうございました！
