### ISSUE TITLE
style_gan2_pytorch/simple_upfirdn_2d.pyについて

### ISSUE THREAD

**Issue by kazukiyamaji** [ayukat1016/gan_sample#17]
simple_upfirdn_2d.py内のforward関数内の処理で、

>＃ pad_all = batch_in_ch_pad + in_height_pad + in_h_in_w_pad + in_width_pad + in_w_minor_dim_pad + minor_dim_pad
pad_all = pad00 + pad01 + pad02 + pad03 + pad04 + pad05 + pad06
x_ = F.pad(x_, pad_all)

と書いてあるのですが、pytorchのF.pad(x,pad)はxの後ろの次元から、padの先頭から順に決められた数でpadを取るので、正式にはコメントは

> #pad_all=minor_dim_pad+in_w_minor_dim_pad +in_width_pad+ in_h_in_w_pad + in_height_pad+batch_in_ch_pad

となるのではないのでしょうか。

また、

>  in_height_pad = [max(pady0, 0), max(pady1, 0)]
        in_width_pad = [max(padx0, 0), max(padx1, 0)]
        pad_crop = pad00 + in_height_pad + in_width_pad + pad06
        x_ = F.pad(x_, pad_crop)

の処理も同様で、
この処理だと、in_height_padでwidthのpadを作り、in_width_padでheightのpadを作るようになっていると思われます。

間違っていたら申し訳ございません。

**Comment by hiroki-shimada-2022** [comment]
ご指摘ありがとうございます。

```
＃ pad_all = batch_in_ch_pad + in_height_pad + in_h_in_w_pad + in_width_pad + in_w_minor_dim_pad + minor_dim_pad
pad_all = pad00 + pad01 + pad02 + pad03 + pad04 + pad05 + pad06
```
上記についてはコメントが間違っていました


```
n_height_pad = [max(pady0, 0), max(pady1, 0)]
in_width_pad = [max(padx0, 0), max(padx1, 0)]
pad_crop = pad00 + in_height_pad + in_width_pad + pad06
x_ = F.pad(x_, pad_crop)
```
上記については
```
pad_crop = pad00 + in_width_pad + in_height_pad + pad06
```
が正しい処理となります

**Comment by h-s-dev** [comment]
ご指摘ありがとうございます。
```
＃ pad_all = batch_in_ch_pad + in_height_pad + in_h_in_w_pad + in_width_pad + in_w_minor_dim_pad + minor_dim_pad
pad_all = pad00 + pad01 + pad02 + pad03 + pad04 + pad05 + pad06
```
上記についてはコメントが間違っていました

```
n_height_pad = [max(pady0, 0), max(pady1, 0)]
in_width_pad = [max(padx0, 0), max(padx1, 0)]
pad_crop = pad00 + in_height_pad + in_width_pad + pad06
x_ = F.pad(x_, pad_crop)
```
上記については
```
pad_crop = pad00 + in_width_pad + in_height_pad + pad06
```
が正しい処理となります
