### ISSUE TITLE
photo2portraitデータセットにアクセスできません

### ISSUE THREAD

**Issue by chappy0205** [ayukat1016/gan_sample#18]
section5_2_cycleGAN.ipynbをGoogle Colabから、実行しようとしたのですが、以下のgdownのコマンドで、Access deniedのErrorが出てしまいました。

```
# photo2portraitデータセットのコピー
!gdown --id 1arF3guFms5tLiaIs8GtcV2dW0WAvrvLM
```

エラーの内容は、以下になります。

```
/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1arF3guFms5tLiaIs8GtcV2dW0WAvrvLM 
```

githubのリンクからもphoto2portraitデータセットにアクセスしようとしたのですが、やはり、アクセスできませんでした。
ご対応、よろしくお願いいたします。

**Comment by takaaki5564** [comment]
ご迷惑をかけ申し訳ありません。リンク先が変更してしまったようです。

下記コマンドで試してみていただけますでしょうか？
!gdown --id 1arF3guFms5tLiaIs8GtcV2dW0WAvrvLM
または下記リンクでダウンロード可能です。
https://drive.google.com/file/d/13qICIuYxV4babtPLjkmg-Y4DzU8_D5wN/view?usp=sharing

もし上記にて問題なければ、コードの方を修正させていただきます。
よろしくお願いいたします。

**Comment by takaaki5564** [comment]
失礼しました。またリンクが切れていたので、再アップロードして上記リンクを変更しました。

**Comment by takaaki5564** [comment]
リンクを修正しましたのでクローズします。
