### ISSUE TITLE
section6_3_recycleGAN_pytorch_face.ipynbのReplayBufferが誤っている？

### ISSUE THREAD

**Issue by itsuki8914** [ayukat1016/gan_sample#19]
section6_3_recycleGAN_pytorch_face.ipynbの、学習を行うコードブロックにてReplayBufferが間違っているのではないかと思ったので確認させていただきたいのですが、

（現在のバージョン）
`fake_B1 = fake_A_buffer.push_and_pop(fake_B1)`

ではなく

`fake_B1 = fake_B_buffer.push_and_pop(fake_B1)`

ではないでしょうか？(B2, B3についても同様）
書籍と異なるデータセットを用いたらうまく学習しなかったのでご連絡させていただきました。
ご確認のほどよろしくお願いします。

**Comment by masataka46** [comment]
ご指摘ありがとうございます。
おっしゃる通り、
```
fake_B1 = fake_A_buffer.push_and_pop(fake_B1)
fake_B2 = fake_A_buffer.push_and_pop(fake_B2)
fake_B3 = fake_A_buffer.push_and_pop(fake_B3)
```
は間違いで
```
fake_B1 = fake_B_buffer.push_and_pop(fake_B1)
fake_B2 = fake_B_buffer.push_and_pop(fake_B2)
fake_B3 = fake_B_buffer.push_and_pop(fake_B3)
```
になります。
コードにも反映させました。ありがとうございました。
