### ISSUE TITLE
AnoGAN　Fruits-360 dataset をダウンロードできない？

### ISSUE THREAD

**Issue by hirokihosoi** [ayukat1016/gan_sample#21]
本書のAnoGANを試しています。
私のほうが初見者のため、恐れ入りますが下記を教えて頂きたいです。
Fruit-360 datasetのダウンロードが実施できない状態です。
以下の症状ですが、知見がございましたら、よろしくお願いします

＜コード：初めの所＞
!wget https://md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com/rp73yg93n8-1.zip -nc -P ./data/
!unzip -n ./data/rp73yg93n8-1.zip -d ./data/
!unzip -n -q ./data/fruits-360_dataset.zip -d ./data/ 

＜エラー内容＞
--2023-01-23 13:36:54--  https://md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com/rp73yg93n8-1.zip
Resolving md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com (md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com)... 52.92.2.34, 52.92.19.130, 3.5.69.108, ...
Connecting to md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com (md-datasets-cache-zipfiles-prod.s3.eu-west-1.amazonaws.com)|52.92.2.34|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-23 13:36:54 ERROR 404: Not Found.

unzip:  cannot find or open ./data/rp73yg93n8-1.zip, ./data/rp73yg93n8-1.zip.zip or ./data/rp73yg93n8-1.zip.ZIP.
unzip:  cannot find or open ./data/fruits-360_dataset.zip, ./data/fruits-360_dataset.zip.zip or ./data/fruits-360_dataset.zip.ZIP.

**Comment by ayukat1016** [comment]
ご連絡ありがとうございます。毛利です。

現在、修正版PRの対応を進めてます。今週中にはNotebookが最新化する予定なので、
お待ち頂ければと思います。

**Comment by massy103** [comment]
ご報告ありがとうございます！！

こちらのPRにて修正して、mainに取り込みました！
お手数ですが、最新版で再度cloneいただけますと幸いです。


https://github.com/ayukat1016/gan_sample/pull/20

**Comment by hirokihosoi** [comment]
ayuka1016様　massy103様
お世話になります。早急なご対応まことにありがとうございます。
ご対応頂いた物私の方でも実行できました。本書購入してよかったです。

**Comment by massy103** [comment]
@hirokihosoi 

解決できたようで良かったです！ (issueは解決済みとして閉じさせていただきます)

嬉しいお言葉をいただきありがとうございます！
またお困りのことがありましたらお問い合わせください。
