### ISSUE TITLE
出力の名称について

### ISSUE THREAD

**Issue by natty5918** [ayukat1016/gan_sample#22]
勉強させていただいております。ありがとうございます！
初歩のところで質問させていただきます。
p.74
識別器Dで本物画像に対する出力は、fake画像のそれの出力の名称と同様にoutputとしているようです。
これってerrDの逆伝播を行うときにどのoutputに伝播するかなどの影響ないでしょうか（backwardsのoverwriteは発生しないですよね？）？
（make_dotとかで伝播の図を見てみたら問題ないようですが）
ご教示いただければ幸いです。

 Arcurid

**Comment by ayukat1016** [comment]
@natty5918 
お問い合わせありがとうございます。3章担当の毛利です。
お返事が遅くなり、失礼しました。

識別器の出力値outputの件、本物画像と偽物画像の双方でoutputになっています。
これは執筆時にPyTorchの公式実装とコーディングを揃えたためです。公式に忠実な実装なため、誤動作する可能性は低いと考えています。
https://pytorch.org/tutorials/beginner/dcgan_faces_tutorial.html

本物画像と偽物画像はラベルが異なり、p73のJ^Dの交差エントロピーの片方の項がラベルにより落ちて本物画像の損失と偽物画像の損失が独立です。よって、本物画像の勾配と偽物画像の勾配も独立なため、errDで本物と偽物の誤差を纏めて計算して問題ないという理解です。

**Comment by natty5918** [comment]
毛利 様
詳細に解説していただきありがとうございます！
ご教示の点はクリアになりました。ありがとうございます。
同じ名称を使っていても各error項を計算した時点でもう逆伝播の経路が定まったというふうに理解しておりますが問題ないでしょうか。

**Comment by ayukat1016** [comment]
@natty5918 
返信ありがとうございます。
はい。その理解で問題ありません。
errD_realとerrD_fakeの計算時点で経路が決まります。
