### ISSUE TITLE
section7_1-training.ipynb のエラーについて

### ISSUE THREAD

**Issue by YusukeHashimotoLab** [ayukat1016/gan_sample#23]
素晴らしいコードを公開して頂きまして、ありがとうございます。
とても勉強になっております。

現在、　section7_1-training.ipynb　を試しています。
Colabolatory上、そしてローカルで実行するとともに、以下のエラーが出て止まってしまいます。

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4, 1, 1, 512, 4, 4]], which is output 0 of AsStridedBackward0, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

これは私だけでしょうか。
誠に恐縮ですが、アドバイスいただけると幸いです。

**Comment by h-s-dev** [comment]
お問い合わせありがとうございます
ローカルで実行した際の環境を教えて頂けますでしょうか？
Pythonのバージョン、PyTorch、その他のライブラリのバージョンが分かりましたらお願いします

**Comment by YusukeHashimotoLab** [comment]
お返事、ありがとうございます。
以下に、関係ありそうなライブラリのバージョンを添付させて頂きます。

lightgbm==3.3.5
matplotlib==3.7.1
matplotlib-inline==0.1.6
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
opencv-python==4.7.0.72
pandas==1.5.3
plotly==5.13.1
scikit-learn==1.2.1
scipy==1.10.1
tensorboard==2.12.0
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
torch==1.13.1
torchsummary==1.5.1
torchvision==0.14.1
tqdm==4.65.0


念の為、以下に、全てのライブラリのバージョンも添付させて頂きます。
ご検討の程どうぞ、よろしくお願いいたします。

absl-py==1.4.0
alembic==1.10.2
asttokens==2.2.1
backcall==0.2.0
cachetools==5.3.0
certifi==2022.12.7
charset-normalizer==3.1.0
cmaes==0.9.1
colorlog==6.7.0
contourpy==1.0.7
cycler==0.11.0
decorator==5.1.1
dnspython==2.3.0
emmet-core==0.49.1
executing==1.2.0
fonttools==4.39.0
future==0.18.3
google-auth==2.16.2
google-auth-oauthlib==0.4.6
greenlet==2.0.2
grpcio==1.51.3
idna==3.4
ipython==8.11.0
jedi==0.18.2
joblib==1.2.0
jsonpatch==1.32
jsonpointer==2.3
kiwisolver==1.4.4
latexcodec==2.0.1
lightgbm==3.3.5
Mako==1.2.4
Markdown==3.4.1
MarkupSafe==2.1.2
matminer==0.8.0
matplotlib==3.7.1
matplotlib-inline==0.1.6
monty==2022.9.9
mp-api==0.30.10
mpmath==1.3.0
msgpack==1.0.5
networkx==3.0
numpy==1.24.2
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.2
opencv-python==4.7.0.72
optuna==3.1.0
packaging==23.0
palettable==3.3.0
pandas==1.5.3
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.4.0
plotly==5.13.1
prompt-toolkit==3.0.38
protobuf==4.22.1
ptyprocess==0.7.0
pure-eval==0.2.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybtex==0.24.0
pydantic==1.10.6
Pygments==2.14.0
pymatgen==2023.3.10
pymongo==4.3.3
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.7.1
PyYAML==6.0
requests==2.28.2
requests-oauthlib==1.3.1
rsa==4.9
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-learn==1.2.1
scipy==1.10.1
six==1.16.0
spglib==2.0.2
SQLAlchemy==2.0.5.post1
stack-data==0.6.2
sympy==1.11.1
tabulate==0.9.0
tenacity==8.2.2
tensorboard==2.12.0
tensorboard-data-server==0.7.0
tensorboard-plugin-wit==1.8.1
threadpoolctl==3.1.0
torch==1.13.1
torchsummary==1.5.1
torchvision==0.14.1
tornado==6.2
tqdm==4.65.0
traitlets==5.9.0
typing_extensions==4.5.0
uncertainties==3.1.7
urllib3==1.26.14
visdom==0.2.4
wcwidth==0.2.6
websocket-client==1.5.1
Werkzeug==2.2.3

**Comment by h-s-dev** [comment]
上記の情報によるとtorch==1.13.1が使用されています。
こちらが動作を確認したのはtorch==1.8.1となりますので、
下記のrequirements.txtで環境を揃えて実行しても同様のエラーが発生するか、ご確認頂けますでしょうか？
https://github.com/ayukat1016/gan_sample/blob/main/chapter7/requirements.txt

1.13.1については別途調査してみます。

**Comment by onozuka777** [comment]
Google Colaboratoryのバージョンが新しくなり、Pytorch==1.8.1はインストールできない仕様になってしまったようです。なんとかプログラムが動くようにしたいのですが、どこを書き換えればよいかわからず、、、ご教示いただけますと幸いです。何卒、よろしくお願い申し上げます。

**Comment by h-s-dev** [comment]
@onozuka777 
現在、多忙につき対応までお待ちください

**Comment by massy103** [comment]
@onozuka777 

お世話になっております🙇‍♂️
また、本書をご購入いただきありがとうございます。

共著者のものです。
ご指摘の通り、colabのpythonのバージョンが3.10になってしまったため、[インストール可能なpytorchのバージョン](https://download.pytorch.org/whl/torch/)が1.10からになってしまったようでした。

[こちらの記事](https://qiita.com/mihara-shoko/items/0e5375644004a8bfccd5)を参考にcolabのpythonバージョンを以下の手順で3.8に下げてみたところ、1.8.1のインストールに成功したので、こちらの手順を試してみていただけますと幸いです。

お手数おかけしますがよろしくお願いいたします！

```
!sudo update-alternatives --config python3
```
![image](https://github.com/ayukat1016/gan_sample/assets/42464037/e82322e8-13b5-4f1f-b806-18e69993842f)


```
# pythonのバージョン確認
!python -V
```

```
# pipが消えてしまうため再インストール
!curl -kL https://bootstrap.pypa.io/get-pip.py | python
!pip -V
```

```
!pip install torch==1.8.1
```

![image](https://github.com/ayukat1016/gan_sample/assets/42464037/7fa73fec-ca16-4ab7-a6c7-3a1e56943eff)

**Comment by h-s-dev** [comment]
対応が遅くなりまして申し訳ありません。
現状の環境でも動作するようにコードを修正しました
