### ISSUE TITLE
Updating: gan_sample/chapter7/requirements.txt

### ISSUE THREAD

**Issue by idomic** [ayukat1016/gan_sample#24]
It might make more sense to update from `ipython-sql` to `Jupysql`.
Adding [more context](https://github.com/catherinedevlin/ipython-sql#legacy-project).

This transition should help you avoid compatibility issues and get access to newer features.
Just switching the name and version as backward compatibility is on.

**Comment by h-s-dev** [comment]
thank you for your advice
I would like to take the opportunity to update
