### ISSUE TITLE
電子書籍

### ISSUE THREAD

**Issue by ryusukecp3** [ayukat1016/gan_sample#8]
電子書籍を出すとしたら、いつぐらいでしょうか？

**Comment by ayukat1016** [comment]
お問い合わせありがとうございます。出版社に問い合わせしましたので、お待ちください。
出版社の返信に多少日数を要する場合があるので、気長にお待ち頂ければと思います。

**Comment by ayukat1016** [comment]
出版社（秀和システム）から返信ありました。現在準備中で3月末くらいになるそうです。

**Comment by ayukat1016** [comment]
電子書籍の件、出版社に本日状況を確認したところ、4月末になりそうです。
お待たせして恐縮ですが、よろしくお願いいたします。

**Comment by ayukat1016** [comment]
電子書籍が発売されたので、クローズします。
https://www.amazon.co.jp/GAN%E3%83%87%E3%82%A3%E3%83%BC%E3%83%97%E3%83%A9%E3%83%BC%E3%83%8B%E3%83%B3%E3%82%B0%E5%AE%9F%E8%A3%85%E3%83%8F%E3%83%B3%E3%83%89%E3%83%96%E3%83%83%E3%82%AF-%E6%AF%9B%E5%88%A9%E6%8B%93%E4%B9%9F-ebook/dp/B09L7P5238/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=&sr=
